import { test, expect } from '@playwright/test'
test.skip(process.env.E2E_DATA_MODE === 'api', 'Suíte exclusiva do modo mock')
test('cliente solicita serviço e freelancer aceita, executa; cliente confirma e avalia', async ({
  page,
}) => {
  await page.goto('/login')
  await page.getByRole('button', { name: 'Cliente', exact: true }).click()
  await page.goto('/servicos/12/solicitar')
  await page
    .getByLabel('Descrição da demanda')
    .fill('Preciso de instalação no apartamento da demonstração.')
  await page.getByRole('button', { name: 'Confirmar solicitação' }).click()
  await expect(page.getByRole('heading', { name: 'Solicitação enviada' })).toBeVisible()
  await page.getByRole('link', { name: 'Acompanhar contratação' }).click()
  const contractUrl = page.url()
  await page.getByRole('button', { name: 'Sair da conta' }).click()
  await page.goto('/login')
  await page.getByRole('button', { name: 'Freelancer', exact: true }).click()
  await page.goto(contractUrl)
  await page.getByRole('button', { name: 'Aceitar solicitação' }).click()
  await page.getByRole('button', { name: 'Iniciar serviço' }).click()
  await page.getByRole('link', { name: 'Marcar como concluído' }).click()
  await page.getByRole('button', { name: 'Confirmar conclusão' }).click()
  await page.getByRole('button', { name: 'Sair da conta' }).click()
  await page.goto('/login')
  await page.getByRole('button', { name: 'Cliente', exact: true }).click()
  await page.goto(contractUrl)
  await page.getByRole('link', { name: 'Confirmar ou contestar' }).click()
  await page.getByRole('button', { name: 'Confirmar recebimento' }).click()
  await page.getByRole('link', { name: 'Avaliar serviço' }).click()
  await page.getByRole('button', { name: '4 estrelas', exact: true }).click()
  await page.getByLabel('Comentário').fill('Serviço concluído conforme o combinado.')
  await page.getByRole('button', { name: 'Enviar avaliação' }).click()
  await expect(page.getByRole('heading', { name: 'Avaliação publicada' })).toBeVisible()
})
test('rascunho não aparece na busca e publicação o torna disponível', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('button', { name: 'Freelancer', exact: true }).click()
  await page.goto('/meus-servicos/novo')
  await page.getByLabel('Título do serviço').fill('Pintura de teste da equipe')
  await page.getByLabel('Categoria', { exact: false }).selectOption({ label: 'Pintura' })
  await page.getByLabel('Descrição detalhada').fill('Pintura para demonstração acadêmica.')
  await page.getByLabel('Valor estimado').fill('200')
  await page.getByRole('button', { name: 'Salvar rascunho' }).click()
  await expect(page.getByText('Rascunho', { exact: true })).toBeVisible()
  await page.goto('/servicos?q=Pintura%20de%20teste%20da%20equipe')
  await expect(page.getByRole('heading', { name: 'Pintura de teste da equipe' })).toHaveCount(0)
  await page.goto('/meus-servicos')
  await page
    .locator('article')
    .filter({ hasText: 'Pintura de teste da equipe' })
    .getByRole('button', { name: 'Publicar', exact: true })
    .click()
  await page.goto('/servicos?q=Pintura%20de%20teste%20da%20equipe')
  await expect(page.getByRole('heading', { name: 'Pintura de teste da equipe' })).toBeVisible()
})
test('mobile, acesso restrito e sessão expirada', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(
    page.getByRole('heading', { name: 'Encontre quem resolve o que você precisa.' }),
  ).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(
    true,
  )
  await page.goto('/login')
  await page.getByRole('button', { name: 'Cliente', exact: true }).click()
  await page.goto('/meus-servicos')
  await expect(page.getByRole('heading', { name: 'Acesso restrito' })).toBeVisible()
  await page.getByRole('button', { name: 'Abrir menu' }).click()
  await expect(page.getByRole('button', { name: 'Sair da conta' })).toBeVisible()
  await page.evaluate(() => {
    const s = JSON.parse(sessionStorage.getItem('fln-session')!)
    s.expiresAt = Date.now() - 1000
    sessionStorage.setItem('fln-session', JSON.stringify(s))
  })
  await page.reload()
  await expect(page).toHaveURL(/\/login$/)
})
